# Generated by Django 3.0.4 on 2020-03-31 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='NEW', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Highest')], default=0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='NEW', max_length=6)),
                ('points', models.PositiveIntegerField()),
                ('_type', models.CharField(choices=[('STORY', 'Story'), ('BUG', 'Bug')], default='STORY', max_length=5)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'Default User'), ('READ', 'Read Only')], default='USER', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Highest')], default=0)),
                ('hours_completed', models.PositiveIntegerField()),
                ('hours_left', models.PositiveIntegerField()),
                ('original_estimate', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='NEW', max_length=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Item')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Project'),
        ),
    ]
