# Generated by Django 3.0.4 on 2020-04-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='_type',
            new_name='item_type',
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='boards.Project'),
        ),
        migrations.AlterField(
            model_name='item',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boards.Feature'),
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.Item'),
        ),
    ]
